services:
  - type: web
    name: tasbih-bot
    env: node
    buildCommand: apt-get install -y chromium && npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: CHROME_PATH
        value: /usr/bin/chromium